name: 01-code_review_approved

on:
  workflow_run:
    workflows: ["code-review-approved-gate-wf"]
    types: [completed]
    branches: 
      - master
      - main

concurrency:
  group: code-review-approved
  cancel-in-progress: true

jobs:
  binary-build:
    uses: ./.github/workflows/b-binary-build-and-e2e-tests.yaml
    with:
      COMPONENT_NAME: kubescape
      CGO_ENABLED: 1
      GO111MODULE: ""
      GO_VERSION: "1.19"
      RELEASE: ${{ github.ref_name}}
      CLIENT: test
    secrets: inherit

  merge-to-master:
    needs: binary-build
    env:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    if: ${{ (always() && (contains(needs.*.result, 'success') || contains(needs.*.result, 'skipped')) && !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled'))) }}
    runs-on: ubuntu-latest
    steps:
      - name: merge-to-master
        if: ${{ env.GH_PERSONAL_ACCESS_TOKEN }}
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "Merge to master - PR number: {pullRequest.number}"
          MERGE_ERROR_FAIL: "true"
          MERGE_METHOD: "merge"
          MERGE_LABELS: ""
          UPDATE_LABELS: ""


          